before_build:
  - nuget restore

build:
  verbosity: normal
  project: Sprung\Sprung.csproj
  
artifacts:
  - path: '**.exe'
    
after_build:
  - cmd: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe" SprungSetup\SprungSetup.vdproj /Build Debug'
